const MAX_PLAYERS_PER_ROOM = 5;
const MIN_PLAYERS_TO_START = 2;
const STARTING_LIVES = 2;
const TURN_TIMER_SECONDS = 15;
const MIN_WORD_LENGTH = 2;
const MAX_HINTS_PER_PRACTICE_SESSION = 3;
const ROOM_CODE_LENGTH = 6;
const MAX_DISPLAY_NAME_LENGTH = 10;
const DIFFICULTY_SWITCH_SECONDS = 65;

module.exports = {
  MAX_PLAYERS_PER_ROOM,
  MIN_PLAYERS_TO_START,
  STARTING_LIVES,
  TURN_TIMER_SECONDS,
  MIN_WORD_LENGTH,
  MAX_HINTS_PER_PRACTICE_SESSION,
  ROOM_CODE_LENGTH,
  MAX_DISPLAY_NAME_LENGTH,
  DIFFICULTY_SWITCH_SECONDS
};
