// Extra words: countries, cities, states, and generic names
// All entries are lowercase, single-word, alphabetic only (/^[a-z]+$/)

const countries = [
  'afghanistan', 'albania', 'algeria', 'andorra', 'angola', 'argentina',
  'armenia', 'australia', 'austria', 'azerbaijan', 'bahamas', 'bahrain',
  'bangladesh', 'barbados', 'belarus', 'belgium', 'belize', 'benin',
  'bhutan', 'bolivia', 'botswana', 'brazil', 'brunei', 'bulgaria',
  'burundi', 'cambodia', 'cameroon', 'canada', 'chad', 'chile',
  'china', 'colombia', 'comoros', 'congo', 'croatia', 'cuba',
  'cyprus', 'denmark', 'djibouti', 'dominica', 'ecuador', 'egypt',
  'eritrea', 'estonia', 'eswatini', 'ethiopia', 'fiji', 'finland',
  'france', 'gabon', 'gambia', 'georgia', 'germany', 'ghana',
  'greece', 'grenada', 'guatemala', 'guinea', 'guyana', 'haiti',
  'honduras', 'hungary', 'iceland', 'india', 'indonesia', 'iran',
  'iraq', 'ireland', 'israel', 'italy', 'jamaica', 'japan',
  'jordan', 'kazakhstan', 'kenya', 'kiribati', 'kuwait', 'kyrgyzstan',
  'laos', 'latvia', 'lebanon', 'lesotho', 'liberia', 'libya',
  'liechtenstein', 'lithuania', 'luxembourg', 'madagascar', 'malawi', 'malaysia',
  'maldives', 'mali', 'malta', 'mauritania', 'mauritius', 'mexico',
  'micronesia', 'moldova', 'monaco', 'mongolia', 'montenegro', 'morocco',
  'mozambique', 'myanmar', 'namibia', 'nauru', 'nepal', 'netherlands',
  'nicaragua', 'niger', 'nigeria', 'norway', 'oman', 'pakistan',
  'palau', 'panama', 'paraguay', 'peru', 'philippines', 'poland',
  'portugal', 'qatar', 'romania', 'russia', 'rwanda', 'samoa',
  'senegal', 'serbia', 'seychelles', 'singapore', 'slovakia', 'slovenia',
  'somalia', 'spain', 'sudan', 'suriname', 'sweden', 'switzerland',
  'syria', 'taiwan', 'tajikistan', 'tanzania', 'thailand', 'togo',
  'tonga', 'tunisia', 'turkey', 'turkmenistan', 'tuvalu', 'uganda',
  'ukraine', 'uruguay', 'uzbekistan', 'vanuatu', 'venezuela', 'vietnam',
  'yemen', 'zambia', 'zimbabwe'
];

const cities = [
  // World Capitals & Metros
  'tokyo', 'delhi', 'newdelhi', 'shanghai', 'mumbai', 'beijing', 'cairo',
  'dhaka', 'osaka', 'karachi', 'chongqing', 'istanbul', 'buenos', 'buenosaires',
  'kolkata', 'kinshasa', 'lagos', 'manila', 'tianjin', 'guangzhou',
  'lahore', 'bangalore', 'bengaluru', 'shenzhen', 'moscow', 'chennai', 'bogota',
  'paris', 'jakarta', 'lima', 'bangkok', 'hyderabad', 'london',
  'tehran', 'chicago', 'chengdu', 'nanjing', 'wuhan', 'nagoya',
  'houston', 'phoenix', 'hangzhou', 'riyadh', 'surat', 'ahmedabad',
  'madrid', 'toronto', 'santiago', 'sydney', 'dallas', 'chattogram',
  'barcelona', 'philadelphia', 'melbourne', 'alexandria', 'xiamen', 'berlin',
  'montreal', 'ankara', 'pune', 'jaipur', 'lucknow', 'kanpur',
  'dubai', 'munich', 'milan', 'nairobi', 'singapore', 'rome',
  'lisbon', 'vienna', 'amsterdam', 'seoul', 'brussels', 'warsaw',
  'prague', 'budapest', 'bucharest', 'dublin', 'helsinki', 'oslo',
  'copenhagen', 'stockholm', 'zurich', 'geneva', 'kyoto', 'yokohama',
  'sapporo', 'hiroshima', 'fukuoka', 'kobe', 'kawasaki', 'sendai',
  'doha', 'muscat', 'amman', 'beirut', 'damascus', 'baghdad',
  'kabul', 'tashkent', 'baku', 'tbilisi', 'yerevan', 'almaty',
  'bishkek', 'dushanbe', 'ashgabat', 'dhanbad', 'agra', 'varanasi',
  'nashik', 'meerut', 'rajkot', 'jodhpur', 'raipur', 'coimbatore',
  'visakhapatnam', 'vizag', 'bhopal', 'patna', 'nagpur', 'indore', 'thane',
  'guwahati', 'chandigarh', 'vadodara', 'ludhiana', 'madurai', 'ranchi',
  'gwalior', 'mysore', 'mysuru', 'jabalpur', 'trivandrum', 'thiruvananthapuram',
  'mangalore', 'mangaluru', 'kochi', 'cochin', 'calicut', 'kozhikode',
  'denver', 'detroit', 'boston', 'seattle', 'minneapolis', 'tampa',
  'orlando', 'atlanta', 'miami', 'portland', 'sacramento', 'austin',
  'nashville', 'baltimore', 'charlotte', 'columbus', 'indianapolis', 'jacksonville',
  'memphis', 'milwaukee', 'raleigh', 'richmond', 'pittsburgh', 'cincinnati',
  'louisville', 'cleveland', 'tucson', 'tulsa', 'oakland', 'honolulu',
  'anchorage', 'buffalo', 'newark', 'norfolk', 'spokane', 'reno',
  'boise', 'savannah', 'charleston', 'burlington', 'providence', 'hartford',
  'manchester', 'birmingham', 'liverpool', 'leeds', 'glasgow', 'edinburgh',
  'cardiff', 'belfast', 'bristol', 'nottingham', 'sheffield', 'newcastle',
  'cambridge', 'oxford', 'brighton', 'southampton', 'leicester', 'aberdeen',
  'marseille', 'lyon', 'toulouse', 'nice', 'nantes', 'strasbourg',
  'bordeaux', 'lille', 'hamburg', 'cologne', 'frankfurt', 'stuttgart',
  'dusseldorf', 'leipzig', 'hanover', 'nuremberg', 'dresden', 'bremen',
  'florence', 'naples', 'turin', 'venice', 'genoa', 'bologna',
  'palermo', 'verona', 'malaga', 'valencia', 'seville', 'bilbao',
  'perth', 'brisbane', 'adelaide', 'canberra', 'hobart', 'auckland',
  'wellington', 'christchurch', 'winnipeg', 'calgary', 'edmonton', 'ottawa',
  'vancouver', 'quebec', 'guadalajara', 'monterrey', 'cancun', 'medellin',
  'quito', 'guayaquil', 'caracas', 'havana', 'kingston', 'nassau',
  'montevideo', 'asuncion', 'accra', 'casablanca', 'tunis', 'algiers',
  'kampala', 'lusaka', 'harare', 'maputo', 'windhoek', 'gaborone',
  'pretoria', 'durban', 'johannesburg', 'capetown', 'freetown', 'dakar',
  'conakry', 'bamako', 'niamey', 'abuja', 'douala', 'libreville',
  'brazzaville', 'lubumbashi', 'mogadishu', 'khartoum', 'addis', 'addisababa',
  'kathmandu', 'colombo', 'yangon', 'mandalay', 'hanoi', 'saigon', 'hochiminh',
  'phnom', 'phnompenh', 'vientiane', 'kuala', 'kualalumpur', 'surabaya', 'bandung', 'makassar',
  'cebu', 'davao', 'taipei', 'kaohsiung', 'taichung', 'busan',
  'incheon', 'daegu', 'ulaanbaatar', 'vladivostok', 'novosibirsk',
  'yekaterinburg', 'kazan', 'samara', 'rostov', 'volgograd',
  'omsk', 'chelyabinsk', 'krasnoyarsk', 'perm', 'voronezh', 'saratov',

  // United States & North America
  'newyork', 'losangeles', 'sanantonio', 'sandiego', 'sanjose', 'sanfrancisco',
  'lasvegas', 'fortworth', 'elpaso', 'albuquerque', 'fresno', 'mesa', 'kansas',
  'kansascity', 'colorado', 'coloradosprings', 'longbeach', 'virginia', 'bakersfield',
  'wichita', 'arlington', 'aurora', 'neworleans', 'anaheim', 'lexington', 'stockton',
  'corpus', 'corpuschristi', 'henderson', 'stpaul', 'greensboro', 'plano', 'lincoln',
  'irvine', 'toledo', 'jersey', 'jerseycity', 'durham', 'chulavista', 'madison',
  'lubbock', 'chandler', 'scottsdale', 'glendale', 'gilbert', 'winston', 'salem',
  'northlasvegas', 'chesapeake', 'garland', 'irving', 'hialeah', 'fremont',
  'batonrouge', 'desmoines', 'tacoma', 'sanbernardino', 'modesto', 'fontana',
  'santaclarita', 'fayetteville', 'rochester', 'oxnard', 'morenovalley', 'huntington',
  'huntingtonbeach', 'saltlake', 'saltlakecity', 'amarillo', 'montgomery', 'grandrapids',
  'huntsville', 'tallahassee', 'knoxville', 'worcester', 'newport', 'bridgeport',
  'newhaven', 'stamford', 'fairbanks', 'juneau', 'hilo', 'siouxfalls', 'fargo',
  'billings', 'cheyenne', 'casper', 'rapidcity', 'bismarck', 'missoula', 'boulder',
  'fortcollins', 'greeley', 'pueblo', 'grandjunction', 'provo', 'orem', 'ogden',
  'stgeorge', 'flagstaff', 'yuma', 'lascruces', 'santafe', 'roswell', 'midland',
  'odessa', 'lubbock', 'abilene', 'waco', 'denton', 'tyler', 'beaumont', 'mcallen',
  'brownsville', 'laredo', 'college', 'collegestation', 'killeen', 'roundrock',
  'sugarland', 'pearland', 'league', 'leaguecity', 'pasadena', 'baytown',

  // Canada & Mexico
  'hamilton', 'kitchener', 'victoria', 'halifax', 'oshawa', 'windsor', 'saskatoon',
  'regina', 'sherbrooke', 'kelowna', 'barrie', 'abbotsford', 'sudbury', 'kingston',
  'saguenay', 'troisrivieres', 'moncton', 'saintjohn', 'stjohns', 'fredericton',
  'charlottetown', 'whitehorse', 'yellowknife', 'iqaluit', 'nanaimo', 'kamloops',
  'princegeorge', 'reddeer', 'lethbridge', 'medicinehat', 'brampton', 'mississauga',
  'markham', 'vaughan', 'richmondhill', 'burnaby', 'surrey', 'laval', 'gatineau',
  'longueuil', 'levis', 'coquitlam', 'waterloo', 'guelph', 'cambridge', 'brantford',
  'mexicocity', 'toluca', 'tijuana', 'leon', 'juarez', 'ciudadjuarez', 'torreon',
  'queretaro', 'sanluispotosi', 'merida', 'mexicali', 'aguascalientes', 'cuernavaca',
  'acapulco', 'tampico', 'chihuahua', 'morelia', 'saltillo', 'veracruz', 'villahermosa',
  'reynosa', 'culiacan', 'hermosillo', 'tuxtla', 'xalapa', 'oaxaca', 'matamoros',
  'mazatlan', 'enseneda', 'durango', 'celaya', 'irapuato', 'campeche', 'pachuca',
  'chetumal', 'colima', 'zacatecas', 'lapaz', 'manzanillo', 'puertovallarta',

  // Central America & Caribbean
  'tegucigalpa', 'sansalvador', 'managua', 'panamacity', 'santiagodecuba', 'portauprince',
  'santodomingo', 'sanjuan', 'bridgetown', 'castries', 'kingstown', 'stgeorges',
  'basseterre', 'roseau', 'belmopan', 'belizecity', 'hamilton', 'cayenne', 'paramaribo',
  'georgetown', 'willemstad', 'oranjestad',

  // South America
  'saopaulo', 'riodejaneiro', 'brasilia', 'salvador', 'fortaleza', 'belohorizonte',
  'manaus', 'curitiba', 'recife', 'portoalegre', 'goiania', 'belem', 'saoluis',
  'maceio', 'natal', 'campinas', 'teresina', 'joaopessoa', 'ribeiraopreto',
  'uberlandia', 'sorocaba', 'aracaju', 'feiradesantana', 'cuiaba', 'joinville',
  'juizdefora', 'londrina', 'niteroi', 'ananindeua', 'belfordroxo', 'florianopolis',
  'macapa', 'santos', 'vilavelha', 'vitoria', 'fozdoiguacu', 'cordoba', 'rosario',
  'mendoza', 'laplata', 'tucuman', 'mardelplata', 'salta', 'santafeciudad', 'parana',
  'posadas', 'neuquen', 'bahia', 'bahiablanca', 'bariloche', 'ushuaia', 'cali',
  'barranquilla', 'cartagena', 'cucuta', 'soledad', 'ibague', 'bucaramanga',
  'pereira', 'valledupar', 'manizales', 'buenaventura', 'pasto', 'monteria',
  'neiva', 'armenia', 'popayan', 'sincelejo', 'floridablanca', 'palmira', 'tunja',
  'arequipa', 'trujillo', 'chiclayo', 'piura', 'iquitos', 'cusco', 'cuzco',
  'chimbote', 'huancayo', 'tacna', 'juliaca', 'ica', 'pucallpa', 'sullana',
  'chincha', 'huanuco', 'ayacucho', 'cajamarca', 'tarapoto', 'tumbes', 'puno',
  'puentealto', 'valparaiso', 'vina', 'vinadelmar', 'antofagasta', 'concepcion',
  'temuco', 'rancagua', 'talca', 'arica', 'chillan', 'iquique', 'copiapo', 'osorno',
  'valdivia', 'puntarenas', 'coquimbo', 'maracaibo', 'valencia', 'barquisimeto',
  'maracay', 'ciudadguayana', 'maturin', 'petare', 'turmero', 'ciudadbolivar',
  'barinas', 'cumana', 'cuenca', 'machala', 'duran', 'manta', 'portoviejo',
  'ambato', 'riobamba', 'loja', 'ibarra', 'esmeraldas', 'cochabamba', 'sucre',
  'elalto', 'oruro', 'tarija', 'potosi', 'ciudaddeleste', 'sanlorenzo', 'luque',
  'encarnacion', 'paysandu', 'laspiedras', 'maldonado', 'puntadeleste',

  // United Kingdom & Ireland
  'coventry', 'bradford', 'hull', 'plymouth', 'stoke', 'wolverhampton', 'derby',
  'swansea', 'salford', 'westminster', 'portsmouth', 'york', 'peterborough', 'dundee',
  'lancaster', 'preston', 'stalbans', 'norwich', 'chester', 'salisbury', 'exeter',
  'gloucester', 'bath', 'canterbury', 'winchester', 'carlisle', 'worcester', 'lincoln',
  'inverness', 'stirling', 'bangor', 'lisburn', 'newry', 'armagh', 'londonderry',
  'bournemouth', 'reading', 'luton', 'northampton', 'miltonkeynes', 'swindon',
  'bolton', 'huddersfield', 'southend', 'middlesbrough', 'blackpool', 'ipswich',
  'telford', 'rotherham', 'colchester', 'warrington', 'watford', 'slough', 'blackburn',
  'chelmsford', 'maidstone', 'poole', 'basingstoke', 'cork', 'galway', 'limerick',
  'waterford', 'drogheda', 'dundalk', 'swords', 'bray', 'navan', 'kilkenny',
  'ennis', 'carlow', 'tralee', 'newbridge', 'portlaoise', 'balbriggan', 'naas',
  'athlone', 'mullingar', 'celbridge', 'wexford', 'letterkenny', 'sligo', 'clonmel',

  // Germany, Austria & Switzerland
  'dortmund', 'essen', 'duisburg', 'bochum', 'wuppertal', 'bielefeld', 'bonn',
  'munster', 'karlsruhe', 'mannheim', 'augsburg', 'wiesbaden', 'gelsenkirchen',
  'monchengladbach', 'braunschweig', 'chemnitz', 'kiel', 'aachen', 'halle',
  'magdeburg', 'freiburg', 'krefeld', 'lubeck', 'oberhausen', 'erfurt', 'mainz',
  'rostock', 'kassel', 'hagen', 'hamm', 'saarbrucken', 'mulheim', 'potsdam',
  'ludwigshafen', 'oldenburg', 'leverkusen', 'osnabruck', 'solingen', 'heidelberg',
  'herne', 'neuss', 'darmstadt', 'paderborn', 'regensburg', 'ingolstadt', 'wurzburg',
  'wolfsburg', 'ulm', 'heilbronn', 'pforzheim', 'gottingen', 'bottrop', 'trier',
  'recklinghausen', 'reutlingen', 'bremerhaven', 'koblenz', 'bergisch', 'jena',
  'remscheid', 'erlangen', 'moers', 'siegen', 'hildesheim', 'salzgitter', 'cottbus',
  'kaiserslautern', 'witten', 'schwerin', 'gera', 'esslingen', 'ludwigsburg',
  'flensburg', 'hanau', 'tubingen', 'marburg', 'konstanz', 'worms', 'passau',
  'baden', 'graz', 'linz', 'salzburg', 'innsbruck', 'klagenfurt', 'villach',
  'wels', 'basel', 'lausanne', 'bern', 'winterthur', 'lucerne', 'stgallen',
  'lugano', 'biel', 'thun', 'schaffhausen', 'chur', 'fribourg', 'neuchatel',

  // France, Belgium & Netherlands
  'montpellier', 'rennes', 'reims', 'saintetienne', 'lehavre', 'toulon', 'grenoble',
  'dijon', 'angers', 'nimes', 'villeurbanne', 'clermont', 'lemans', 'aix', 'brest',
  'tours', 'amiens', 'limoges', 'annecy', 'perpignan', 'boulogne', 'metz', 'besancon',
  'orleans', 'saintdenis', 'argenteuil', 'rouen', 'montreuil', 'mulhouse', 'caen',
  'nancy', 'roubaix', 'tourcoing', 'nanterre', 'avignon', 'vitry', 'creteil',
  'dunkirk', 'poitiers', 'asnieres', 'versailles', 'colombes', 'saintnazaire',
  'aubervilliers', 'pau', 'calais', 'larochelle', 'beziers', 'antibes', 'cannes',
  'colmar', 'bourges', 'valence', 'quimper', 'troyes', 'ajaccio', 'bastia',
  'antwerp', 'ghent', 'charleroi', 'liege', 'bruges', 'namur', 'leuven', 'mons',
  'aalst', 'mechelen', 'kortrijk', 'hasselt', 'sintniklaas', 'oostende', 'tournai',
  'genk', 'roeselare', 'mouscron', 'verviers', 'rotterdam', 'thehague', 'hague',
  'utrecht', 'eindhoven', 'groningen', 'tilburg', 'almere', 'breda', 'nijmegen',
  'enschede', 'haarlem', 'arnhem', 'amersfoort', 'zaanstad', 'shertogenbosch',
  'apeldoorn', 'hoofddorp', 'maastricht', 'leiden', 'dordrecht', 'zoetermeer',
  'zwolle', 'deventer', 'delft', 'alkmaar', 'heerlen', 'venlo', 'leeuwarden',
  'hilversum', 'hengelo', 'amstelveen', 'roosendaal', 'purmerend', 'oss', 'schiedam',
  'spijkenisse', 'helmond', 'vlaardingen', 'alphen', 'gouda', 'zaandam',

  // Spain, Portugal & Italy
  'zaragoza', 'murcia', 'palma', 'alicante', 'cordoba', 'valladolid', 'vigo',
  'gijon', 'hospitalet', 'vitoria', 'coruna', 'granada', 'elche', 'oviedo',
  'badalona', 'cartagena', 'terrassa', 'jerez', 'sabadell', 'santacruz', 'mostoles',
  'alcala', 'pamplona', 'fuenlabrada', 'almeria', 'leganes', 'sansebastian',
  'santander', 'castellon', 'burgos', 'alcorcon', 'albacete', 'getafe', 'salamanca',
  'logrono', 'huelva', 'badajoz', 'tarragona', 'leon', 'lleida', 'cadiz',
  'mataro', 'marbella', 'jaen', 'algeciras', 'torrejon', 'ourense', 'alcobendas',
  'reus', 'torrevieja', 'telde', 'barakaldo', 'lugo', 'girona', 'caceres', 'lorca',
  'coslada', 'talavera', 'cornella', 'aviles', 'palencia', 'pontevedra', 'toledo',
  'orihuela', 'ceuta', 'melilla', 'gandia', 'fuengirola', 'manresa', 'ciudadreal',
  'benidorm', 'ferrol', 'ponferrada', 'zamora', 'segovia', 'cuenca', 'huesca',
  'teruel', 'soria', 'avila', 'ibiza', 'porto', 'vilanovadegaia', 'amadora',
  'braga', 'setubal', 'coimbra', 'queluz', 'funchal', 'casi', 'loures', 'evora',
  'faro', 'aveiro', 'viseu', 'leiria', 'guimaraes', 'bari', 'catania', 'messina',
  'padua', 'trieste', 'brescia', 'taranto', 'prato', 'parma', 'modena', 'reggio',
  'perugia', 'ravenna', 'livorno', 'cagliari', 'foggia', 'rimini', 'salerno',
  'ferrara', 'sassari', 'latina', 'monza', 'siracusa', 'pescara', 'bergamo',
  'forli', 'trento', 'vicenza', 'terni', 'bolzano', 'novara', 'piacenza', 'ancona',
  'andria', 'arezzo', 'udine', 'cesena', 'lecce', 'pesaro', 'barletta', 'alessandria',
  'laspezia', 'pisa', 'pistoia', 'lucca', 'catanzaro', 'brindisi', 'treviso',
  'como', 'busto', 'grosseto', 'sesto', 'varese', 'fiumicino', 'asti', 'caserta',
  'gela', 'aprilia', 'ragusa', 'pavia', 'cremona', 'carpi', 'imola', 'lamezia',
  'laquila', 'trapani', 'cosenza', 'potenza', 'crotone', 'caltanissetta', 'viterbo',
  'carrara', 'fano', 'sanremo', 'savona', 'matera', 'siena', 'benevento', 'olbia',

  // Central, Eastern & Northern Europe
  'krakow', 'lodz', 'wroclaw', 'poznan', 'gdansk', 'szczecin', 'bydgoszcz', 'lublin',
  'katowice', 'bialystok', 'gdynia', 'czestochowa', 'radom', 'sosnowiec', 'torun',
  'kielce', 'gliwice', 'zabrze', 'bytom', 'bielskobiala', 'olsztyn', 'rzeszow',
  'rybnik', 'tychy', 'opole', 'elblag', 'plock', 'walbrzych', 'gorzow', 'wloclawek',
  'tarnow', 'chorzow', 'koszalin', 'kalisz', 'legnica', 'brno', 'ostrava', 'plzen',
  'liberec', 'olomouc', 'ceskebudejovice', 'usti', 'hradec', 'pardubice', 'zlin',
  'havirov', 'kladno', 'most', 'opava', 'karvina', 'jihlava', 'teplice', 'decin',
  'karlovyvary', 'kosice', 'presov', 'zilina', 'nitra', 'banskabystrica', 'trnava',
  'martin', 'trencin', 'poprad', 'prievidza', 'zvolen', 'debrecen', 'szeged',
  'miskolc', 'pecs', 'gyor', 'nyiregyhaza', 'kecskemet', 'szekesfehervar', 'szombathely',
  'szolnok', 'tatabanya', 'kaposvar', 'erd', 'veszprem', 'bekescsaba', 'zalaegerszeg',
  'sopron', 'eger', 'nagykanizsa', 'cluj', 'clujnapoca', 'timisoara', 'iasi',
  'constanta', 'craiova', 'brasov', 'galati', 'ploiesti', 'oradea', 'braila',
  'arad', 'pitesti', 'sibiu', 'bacau', 'targumures', 'baiamare', 'buzau', 'botosani',
  'satumare', 'plovdiv', 'varna', 'burgas', 'ruse', 'starazagora', 'pleven', 'sliven',
  'dobrich', 'shumen', 'pernik', 'haskovo', 'yambol', 'pazardzhik', 'blagoevgrad',
  'thessaloniki', 'patras', 'heraklion', 'larissa', 'volos', 'ioannina', 'trikala',
  'chalcis', 'serres', 'alexandroupoli', 'xanthi', 'katerini', 'kalamata', 'kavala',
  'chania', 'lamia', 'komotini', 'rhodes', 'agrinio', 'drama', 'aarhus', 'odense',
  'aalborg', 'frederiksberg', 'gentofte', 'esbjerg', 'gladsaxe', 'randers', 'kolding',
  'horsens', 'vejle', 'roskilde', 'helsingor', 'herning', 'silkeborg', 'naestved',
  'gothenburg', 'malmo', 'uppsala', 'vasteras', 'orebro', 'linkoping', 'helsingborg',
  'jonkoping', 'norrkoping', 'lund', 'umea', 'gavle', 'boras', 'sodertalje',
  'eskilstuna', 'halmstad', 'vaxjo', 'karlstad', 'sundsvall', 'trollhattan',
  'ostersund', 'lulea', 'kristianstad', 'kalmar', 'falun', 'skovde', 'karlskrona',
  'bergen', 'trondheim', 'stavanger', 'drammen', 'fredrikstad', 'kristiansand',
  'sandnes', 'tromso', 'sarpsborg', 'skien', 'alesund', 'sandefjord', 'haugesund',
  'tonsberg', 'moss', 'porsgrunn', 'bodo', 'arendal', 'hamar', 'larvik', 'halden',
  'harstad', 'molde', 'lillehammer', 'espoo', 'tampere', 'vantaa', 'oulu', 'turku',
  'jyvaskyla', 'lahti', 'kuopio', 'pori', 'kouvola', 'joensuu', 'lappeenranta',
  'hameenlinna', 'vaasa', 'rovaniemi', 'seinajoki', 'mikkeli', 'kotka', 'salo',
  'porvoo', 'kokkola', 'hyvinkaa', 'lohja', 'jarvenpaa', 'reykjavik', 'kopavogur',
  'hafnarfjordur', 'akureyri', 'tartu', 'narva', 'parnu', 'viljandi', 'daugavpils',
  'liepaja', 'jelgava', 'jurmala', 'ventspils', 'kaunas', 'klaipeda', 'siauliai',
  'panevezys', 'alytus', 'marijampole', 'kharkiv', 'odesa', 'odessa', 'dnipro',
  'donetsk', 'zaporizhzhia', 'lviv', 'kryvyirih', 'mykolaiv', 'sevastopol',
  'mariupol', 'luhansk', 'vinnytsia', 'simferopol', 'kherson', 'chernihiv',
  'poltava', 'chernivtsi', 'cherkasy', 'zhytomyr', 'sumy', 'khmelnytskyi',
  'horlivka', 'rivne', 'kamianske', 'kropyvnytskyi', 'ivanofrankivsk', 'kremenchuk',
  'ternopil', 'lutsk', 'kramatorsk', 'melitopol', 'kerch', 'nikopol', 'sloviansk',
  'uzhhorod', 'berdiansk', 'pavlohrad', 'gomel', 'mogilev', 'vitebsk', 'grodno',
  'brest', 'babruysk', 'baranavichy', 'pinsk', 'novisad', 'nis', 'kragujevac',
  'subotica', 'zrenjanin', 'pancevo', 'cacak', 'split', 'rijeka', 'osijek',
  'zadar', 'pula', 'karlovac,', 'varazdin', 'sibenik', 'dubrovnik', 'banjaluka',
  'tuzla', 'zenica', 'mostar', 'bijeljina', 'skopje', 'bitola', 'kumanovo',
  'prilep', 'tetovo', 'ohrid', 'podgorica', 'niksic', 'hercegnovi', 'bar',
  'budva', 'cetinje', 'durres', 'vlore', 'shkoder', 'fier', 'korce', 'elbasan',
  'pristina', 'prizren', 'gjilan', 'peja', 'chisinau', 'tiraspol', 'balti',

  // India & South Asia
  'ghaziabad', 'faridabad', 'pimpri', 'chinchwad', 'kalyan', 'dombivli', 'vasai',
  'virar', 'allahabad', 'prayagraj', 'howrah', 'solapur', 'hubli', 'dharwad',
  'moradabad', 'tiruchirappalli', 'trichy', 'tiruppur', 'gurgaon', 'gurugram',
  'aligarh', 'jalandhar', 'bhubaneswar', 'salem', 'warangal', 'bhiwandi',
  'saharanpur', 'gorakhpur', 'bikaner', 'amravati', 'noida', 'jamshedpur',
  'bhilai', 'cuttack', 'firozabad', 'nellore', 'bhavnagar', 'dehradun',
  'durgapur', 'asansol', 'rourkela', 'nanded', 'kolhapur', 'ajmer', 'akola',
  'gulbarga', 'kalaburagi', 'ujjain', 'siliguri', 'jhansi', 'ulhasnagar',
  'sangli', 'erode', 'belgaum', 'belagavi', 'kurnool', 'ambattur', 'rajahmundry',
  'tirunelveli', 'malegaon', 'gaya', 'udaipur', 'karimnagar', 'muzaffarnagar',
  'mathura', 'patiala', 'bellary', 'ballari', 'korba', 'bokaro', 'muzaffarpur',
  'agartala', 'bhagalpur', 'davanagere', 'dhule', 'shimoga', 'shivamogga',
  'panipat', 'bilaspur', 'shahjahanpur', 'darbhanga', 'thrissur', 'alwar',
  'rohtak', 'kottayam', 'shimla', 'gangtok', 'imphal', 'shillong', 'aizawl',
  'kohima', 'itanagar', 'panaji', 'pondicherry', 'puducherry', 'portblair',
  'silvassa', 'daman', 'diu', 'kargil', 'leh', 'haridwar', 'rishikesh',
  'roorkee', 'nainital', 'mussoorie', 'vrindavan', 'ayodhya', 'haldwani',
  'rudrapur', 'hoshiarpur', 'batala', 'pathankot', 'moga', 'firozpur',
  'kapurthala', 'ambala', 'yamunanagar', 'hisar', 'karnal', 'sonipat',
  'panchkula', 'sirsa', 'jind', 'thanesar', 'kaithal', 'rewari', 'palwal',
  'bhiwani', 'bahadurgarh', 'faisalabad', 'rawalpindi', 'gujranwala', 'peshawar',
  'multan', 'hyderabadpk', 'islamabad', 'quetta', 'bahawalpur', 'sargodha',
  'sialkot', 'sukkur', 'larkana', 'sheikhupura', 'rahimyarkhan', 'jhang',
  'gujrat', 'mardan', 'kasur', 'khulna', 'rajshahi', 'sylhet', 'barishal',
  'rangpur', 'mymensingh', 'cumilla', 'narayanganj', 'gazipur', 'bogura',
  'kandy', 'galle', 'jaffna', 'negombo', 'anuradhapura', 'batticaloa',
  'pokhara', 'lalitpur', 'biratnagar', 'bharatpur', 'birgunj', 'dharan',

  // East & Southeast Asia
  'dongguan', 'foshan', 'shenyang', 'xian', 'harbin', 'suzhou', 'qingdao',
  'dalian', 'zhengzhou', 'shantou', 'jinan', 'changchun', 'kunming', 'changsha',
  'taiyuan', 'hefei', 'shijiazhuang', 'fuzhou', 'wuxi', 'zhongshan', 'wenzhou',
  'nanning', 'nanchang', 'ningbo', 'guiyang', 'lanzhou', 'zibo', 'changzhou',
  'xuzhou', 'tangshan', 'baotou', 'huizhou', 'yantai', 'shaoxing', 'liuzhou',
  'nantong', 'luoyang', 'yangzhou', 'linyi', 'weifang', 'baoding', 'haikou',
  'datong', 'ansan', 'jilin', 'hohhot', 'qiqihar', 'yinchuan', 'xining',
  'urumqi', 'lhasa', 'sanya', 'zhuhai', 'guilin', 'kaifeng', 'anyang',
  'jiaxing', 'huzhou', 'quanzhou', 'putian', 'zhangzhou', 'jiangmen', 'zhanjiang',
  'maoming', 'zhaoqing', 'qingyuan', 'chaozhou', 'jieyang', 'meizhou', 'heyuan',
  'shanwei', 'shaoguan', 'yiwu', 'jinhua', 'taizhou', 'zhoushan', 'weihai',
  'rizhao', 'dandong', 'jinzhou', 'fushun', 'daqing', 'saitama', 'chiba',
  'kitakyushu', 'sakai', 'niigata', 'hamamatsu', 'kumamoto', 'sagamihara',
  'shizuoka', 'okayama', 'kanazawa', 'kagoshima', 'funabashi', 'utsunomiya',
  'matsuyama', 'higashiosaka', 'hachioji', 'nishinomiya', 'ichikawa', 'oita',
  'kurashiki', 'fukuyama', 'amagasaki', 'nagasaki', 'machida', 'toyama', 'toyota',
  'takatsuki', 'gifu', 'kashiwa', 'fujisawa', 'miyazaki', 'toyohashi', 'ichinomiya',
  'wakayama', 'okazaki', 'nara', 'suita', 'takamatsu', 'asahikawa', 'iwaki',
  'koriyama', 'naha', 'tokorozawa', 'gunma', 'aomori', 'maebashi', 'akita',
  'koshigaya', 'yokkaichi', 'kasugai', 'morioka', 'fukushima', 'akashi', 'tsu',
  'shimonoseki', 'nagaoka', 'ichihara', 'hakodate', 'mito', 'yao', 'fukui',
  'sasebo', 'tokushima', 'hiratsuka', 'yamagata', 'kamakura', 'hakone', 'nikko',
  'daejeon', 'gwangju', 'suwon', 'ulsan', 'changwon', 'goyang', 'seongnam',
  'yongin', 'bucheon', 'cheongju', 'jeonju', 'cheonan', 'namyangju', 'hwaseong',
  'anyang', 'pohang', 'uijeongbu', 'siheung', 'pyeongtaek', 'gimhae', 'jinju',
  'gumi', 'yeosu', 'wonju', 'iksan', 'asan', 'gunsan', 'chuncheon', 'suncheon',
  'mokpo', 'gangneung', 'gyeongju', 'geoje', 'gimpo', 'yangsan', 'gwangmyeong',
  'osan', 'paju', 'ichon', 'andong', 'jecheon', 'sokcho', 'tongyeong', 'seogwipo',
  'jeju', 'medan', 'bekasi', 'tangerang', 'depok', 'semarang', 'palembang',
  'batam', 'bogor', 'pekanbaru', 'bandarlampung', 'padang', 'malang', 'denpasar',
  'samarinda', 'tasikmalaya', 'pontianak', 'banjarmasin', 'balikpapan', 'jambi',
  'surakarta', 'solo', 'cimahi', 'manado', 'kupang', 'yogyakarta', 'cilegon',
  'mataram', 'ambon', 'bengkulu', 'palu', 'kendari', 'sukabumi', 'cirebon',
  'pekalongan', 'kediri', 'tegal', 'quezon', 'quezoncity', 'caloocan', 'taguig',
  'antipolo', 'pasig', 'cagayan', 'paranaque', 'valenzuela', 'laspinas', 'makati',
  'bacolod', 'muntinlupa', 'iloilo', 'pasay', 'angeles', 'marikina', 'iligan',
  'mandaluyong', 'lapulapu', 'cabanatuan', 'butuan', 'baguio', 'tarlac', 'batangas',
  'lipa', 'ormoc', 'lucena', 'sanfernando', 'olongapo', 'naga', 'tagum', 'cotabato',
  'generalsantos', 'nonthaburi', 'nakhon', 'chiangmai', 'hatyai', 'udonthani',
  'pakkret', 'siracha', 'phuket', 'pattaya', 'nakhonpathom', 'khonkaen', 'ubon',
  'ubonratchathani', 'nakhonsawan', 'samutprakan', 'songkhla', 'rayong', 'yala',
  'phitsanulok', 'suratthani', 'lampang', 'georgetown', 'penang', 'ipoh', 'shahalam',
  'petalingjaya', 'johorbahru', 'melaka', 'malacca', 'alorsetar', 'kotakinabalu',
  'kuantan', 'kualaterengganu', 'kuching', 'seremban', 'sandakan', 'kluang',
  'taiping', 'bintulu', 'miri', 'muar', 'batupahat', 'kangar', 'labuan',
  'putrajaya', 'cyberjaya', 'haiphong', 'danang', 'cantho', 'bienhoa', 'nhatrang',
  'buanmethuot', 'hue', 'vungtau', 'quynhon', 'longxuyen', 'thainguyen', 'namdinh',
  'phanthiet', 'camranh', 'dalat', 'vinh', 'pleiku', 'rachgia', 'siemreap',
  'battambang', 'sihanoukville', 'luangprabang', 'pakse', 'savannakhet', 'naypyidaw',
  'mawlamyine', 'bago', 'pathein', 'taunggyi', 'sittwe', 'bandarseribegawan', 'dili',

  // Middle East & Central Asia
  'jeddah', 'mecca', 'medina', 'dammam', 'khobar', 'dhahran', 'taif', 'tabuk',
  'buraidah', 'khamis', 'abha', 'yanbu', 'jubail', 'najran', 'hail', 'jizan',
  'hofuf', 'qatif', 'abudhabi', 'sharjah', 'alain', 'ajman', 'rasalkhaimah',
  'fujairah', 'ummalquwain', 'rayyan', 'wakrah', 'seeb', 'salalah', 'sohar',
  'nizwa', 'sur', 'manama', 'muharraq', 'riffa', 'kuwaitcity', 'salmiya',
  'hawalli', 'jahra', 'ahmadi', 'mashhad', 'isfahan', 'karaj', 'shiraz',
  'tabriz', 'qom', 'ahvaz', 'kermanshah', 'urmia', 'rasht', 'zahedan', 'hamadan',
  'kerman', 'yazd', 'ardabil', 'bandarabbas', 'arak', 'zanjan', 'sanandaj',
  'qazvin', 'khorramabad', 'sari', 'gorgan', 'basra', 'mosul', 'erbil',
  'sulaymaniyah', 'kirkuk', 'najaf', 'karbala', 'nasiriyah', 'amarah', 'diwaniyah',
  'kut', 'hilla', 'ramadi', 'fallujah', 'samarra', 'aleppo', 'homs', 'latakia',
  'hama', 'raqqa', 'tartus', 'daraa', 'sweida', 'tripoli', 'sidon', 'tyre',
  'nabatieh', 'baalbek', 'jounieh', 'zahle', 'zarqa', 'irbid', 'aqaba', 'madaba',
  'jerash', 'jerusalem', 'telaviv', 'haifa', 'rishon', 'rishonlezion', 'petah',
  'petahtikva', 'ashdod', 'netanya', 'beersheba', 'holon', 'bneibrak', 'ramatgan',
  'batyam', 'ashkelon', 'herzliya', 'kfar', 'kfarsaba', 'hadera', 'modiin',
  'nazareth', 'lod', 'ramla', 'eilat', 'tiberias', 'gaza', 'gazacity', 'hebron',
  'nablus', 'ramallah', 'jenin', 'bethlehem', 'jericho', 'izmir', 'bursa', 'adana',
  'gaziantep', 'konya', 'antalya', 'kayseri', 'mersin', 'eskisehir', 'diyarbakir',
  'samsun', 'denizli', 'sanliurfa', 'adapazari', 'malatya', 'kahramanmaras',
  'erzurum', 'van', 'batman', 'elazig', 'izmit', 'manisa', 'sivas', 'gebze',
  'balikesir', 'trabzon', 'canakkale', 'corum', 'kutahya', 'osmaniye', 'kirikkale',
  'giresun', 'usak', 'aksaray', 'afyon', 'isparta', 'tekirdag', 'edirne',
  'alanya', 'bodrum', 'marmaris', 'fethiye', 'ganja', 'sumqayit', 'mingachevir',
  'nakhchivan', 'batumi', 'kutaisi', 'rustavi', 'gyumri', 'vanadzor', 'astana',
  'nursultan', 'shymkent', 'karaganda', 'aktobe', 'taraz', 'pavlodar', 'oskemen',
  'semey', 'atyrau', 'kostanay', 'kyzylorda', 'oral', 'aktau', 'temirtau',
  'turkistan', 'kokshetau', 'osh', 'jalalabad', 'karakol', 'tokmok', 'khujand',
  'kulob', 'bokhtar', 'turkmenabat', 'mary', 'dashoguz', 'balkanabat', 'samarkand',
  'namangan', 'andijan', 'nukus', 'bukhara', 'fergana', 'qarshi', 'kokand',
  'termez', 'jizzakh', 'chirchiq', 'urgench', 'kandahar', 'herat', 'mazar',
  'mazarisharif', 'kunduz', 'ghazni', 'erdenet', 'darkhan',

  // Africa
  'giza', 'shubra', 'portsaid', 'suez', 'luxor', 'asyut', 'mansoura', 'tanta',
  'fayoum', 'zagazig', 'ismailia', 'aswan', 'damietta', 'damanhur', 'minya',
  'benisuef', 'qena', 'sohag', 'hurghada', 'sharm', 'sharmelsheikh', 'kano',
  'ibadan', 'kaduna', 'portharcourt', 'benincity', 'maiduguri', 'zaria', 'aba',
  'jos', 'ilorin', 'oyo', 'enugu', 'abeokuta', 'sokoto', 'onitsha', 'warri',
  'osbogbo', 'calabar', 'akure', 'katsina', 'bauchi', 'minna', 'makurdi',
  'owerri', 'yola', 'uyo', 'ife', 'ethekwini', 'ekurhuleni', 'tshwane',
  'portelizabeth', 'gqeberha', 'bloemfontein', 'eastlondon', 'pietermaritzburg',
  'polokwane', 'nelspruit', 'mbombela', 'kimberley', 'rustenburg', 'witbank',
  'welkom', 'george', 'potchefstroom', 'klerksdorp', 'upington', 'paarl',
  'mbujimayi', 'kananga', 'kisangani', 'bukavu', 'goma', 'kolwezi', 'likasi',
  'luanda', 'huambo', 'lobito', 'benguela', 'lubango', 'cabinda', 'mombasa',
  'nakuru', 'eldoret', 'kisumu', 'thika', 'malindi', 'kitale', 'garissa',
  'kakamega', 'nanyuki', 'diredawa', 'mekelle', 'gondar', 'awasa', 'bahirdar',
  'dessie', 'jimma', 'jijiga', 'rabat', 'fes', 'marrakech', 'tangier', 'agadir',
  'meknes', 'oujda', 'kenitra', 'tetouan', 'safi', 'temara', 'mohammedia',
  'eljadida', 'nador', 'oran', 'constantine', 'batna', 'djelfa', 'setif',
  'annaba', 'sidibelabbes', 'biskra', 'tiaret', 'bejaia', 'mostaganem',
  'sfax', 'sousse', 'kairouan', 'bizerte', 'gabes', 'ariana', 'gafsa',
  'monastir', 'kumasi', 'tamale', 'sekondi', 'takoradi', 'ashaiman', 'sunyani',
  'capecoast', 'koforidua', 'tema', 'touba', 'thies', 'rufisque', 'kaolack',
  'mbour', 'ziguinchor', 'saintlouis', 'diourbel', 'mbarara', 'mukono',
  'gulu', 'masaka', 'kasese', 'jinja', 'mbale', 'entebbe', 'daressalaam',
  'mwanza', 'arusha', 'dodoma', 'mbeya', 'morogoro', 'tanga', 'tabora',
  'zanzibar', 'kigoma', 'kigali', 'butare', 'gisenyi', 'kitwe', 'ndola',
  'kabwe', 'chingola', 'livingstone', 'bulawayo', 'chitungwiza', 'mutare',
  'gweru', 'kwekwe', 'masvingo', 'matola', 'nampula', 'beira', 'chimoio',
  'nacala', 'quelimane', 'tete', 'pemba', 'rundu', 'walvisbay', 'oshakati',
  'swakopmund', 'francistown', 'molepolole', 'maun', 'serowe', 'lome',
  'sokode', 'kara', 'cotonou', 'abomey', 'portonovo', 'parakou', 'monrovia',
  'bo', 'kenema', 'makeni', 'nzerekore', 'kankan', 'kindia', 'sikasso',
  'mopti', 'kayes', 'segou', 'maradi', 'zinder', 'tahoua', 'agadez',
  'moundou', 'sarh', 'abeche', 'bangui', 'berberati', 'pointenoire',
  'dolisie', 'portgentil', 'franceville', 'malabo', 'bata', 'hargeisa',
  'bosaso', 'kismayo', 'burao', 'omdurman', 'portsudan', 'kassala',
  'wadmedani', 'moroni', 'praia', 'mindelo', 'saotome', 'portlouis',
  'curepipe', 'antananarivo', 'toamasina', 'antsirabe', 'mahajanga',

  // Australia, New Zealand & Oceania
  'goldcoast', 'sunshinecoast', 'wollongong', 'geelong', 'townsville', 'cairns',
  'toowoomba', 'darwin', 'ballarat', 'bendigo', 'albury', 'wodonga', 'launceston',
  'mackay', 'rockhampton', 'bunbury', 'coffsharbour', 'bundaberg', 'wagga',
  'mildura', 'shepparton', 'portmacquarie', 'gladstone', 'tamworth', 'orange',
  'dubbo', 'geraldton', 'nowra', 'bathurst', 'warrnambool', 'albany', 'devonport',
  'mountgambier', 'kalgoorlie', 'lismore', 'alicesprings', 'brokenhill', 'napier',
  'hastings', 'dunedin', 'palmerston', 'palmerstonnorth', 'nelson', 'rotorua',
  'newplymouth', 'whangarei', 'invercargill', 'whanganui', 'gisborne', 'timaru',
  'blenheim', 'taupo', 'pukekohe', 'masterton', 'levin', 'ashburton', 'queenstown',
  'wanaka', 'suva', 'lautoka', 'nadi', 'labasa', 'portmoresby', 'lae', 'mounthagen',
  'madang', 'goroka', 'honiara', 'portvila', 'noumea', 'papeete', 'apia',
  'nukualofa', 'majuro', 'tarawa', 'palikir', 'funafuti', 'avarua', 'hagatna',
  'saipan', 'koror'
];

const usStates = [
  'alabama', 'alaska', 'arizona', 'arkansas', 'california', 'colorado',
  'connecticut', 'delaware', 'florida', 'georgia', 'hawaii', 'idaho',
  'illinois', 'indiana', 'iowa', 'kansas', 'kentucky', 'louisiana',
  'maine', 'maryland', 'massachusetts', 'michigan', 'minnesota', 'mississippi',
  'missouri', 'montana', 'nebraska', 'nevada', 'ohio', 'oklahoma',
  'oregon', 'pennsylvania', 'tennessee', 'texas', 'utah', 'vermont',
  'virginia', 'washington', 'wisconsin', 'wyoming'
];

const indianStates = [
  'andhra', 'arunachal', 'assam', 'bihar', 'chhattisgarh', 'goa',
  'gujarat', 'haryana', 'himachal', 'jharkhand', 'karnataka', 'kerala',
  'madhya', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
  'odisha', 'punjab', 'rajasthan', 'sikkim', 'tamil', 'telangana',
  'tripura', 'uttarakhand', 'uttar', 'bengal'
];

const genericNames = [
  // Common English/Western names
  'james', 'john', 'robert', 'michael', 'david', 'william', 'richard', 'joseph',
  'thomas', 'charles', 'christopher', 'daniel', 'matthew', 'anthony', 'mark',
  'donald', 'steven', 'andrew', 'paul', 'joshua', 'kenneth', 'kevin', 'brian',
  'george', 'timothy', 'ronald', 'edward', 'jason', 'jeffrey', 'ryan',
  'jacob', 'gary', 'nicholas', 'eric', 'jonathan', 'stephen', 'larry',
  'justin', 'scott', 'brandon', 'benjamin', 'samuel', 'raymond', 'gregory',
  'frank', 'alexander', 'patrick', 'jack', 'dennis', 'jerry', 'tyler',
  'aaron', 'jose', 'adam', 'nathan', 'henry', 'peter', 'zachary',
  'mary', 'patricia', 'jennifer', 'linda', 'barbara', 'elizabeth', 'susan',
  'jessica', 'sarah', 'karen', 'lisa', 'nancy', 'betty', 'margaret',
  'sandra', 'ashley', 'dorothy', 'kimberly', 'emily', 'donna', 'michelle',
  'carol', 'amanda', 'melissa', 'deborah', 'stephanie', 'rebecca', 'sharon',
  'laura', 'cynthia', 'kathleen', 'amy', 'angela', 'shirley', 'anna',
  'brenda', 'pamela', 'emma', 'nicole', 'helen', 'samantha', 'katherine',
  'christine', 'debra', 'rachel', 'carolyn', 'janet', 'catherine', 'maria',
  'heather', 'diane', 'ruth', 'julie', 'olivia', 'joyce', 'virginia',
  'victoria', 'kelly', 'lauren', 'christina', 'joan', 'evelyn', 'judith',
  'megan', 'andrea', 'cheryl', 'hannah', 'jacqueline', 'martha', 'gloria',
  'teresa', 'ann', 'sara', 'madison', 'frances', 'kathryn', 'janice',
  'jean', 'abigail', 'alice', 'grace', 'sophia', 'natalie', 'diana',
  // Common Indian names
  'arjun', 'rahul', 'vikram', 'arun', 'sunil', 'rajesh', 'amit',
  'deepak', 'ravi', 'vijay', 'suresh', 'anil', 'sanjay', 'manoj',
  'ashok', 'kumar', 'mohan', 'ramesh', 'dinesh', 'vivek', 'kiran',
  'anand', 'rohit', 'nitin', 'gaurav', 'varun', 'harsh', 'sahil',
  'aarav', 'aryan', 'ishaan', 'rohan', 'aditya', 'pranav', 'tanmay',
  'priya', 'neha', 'pooja', 'kavita', 'sunita', 'anita', 'rekha',
  'meena', 'geeta', 'sita', 'radha', 'lakshmi', 'sarita', 'nisha',
  'ritu', 'swati', 'anjali', 'divya', 'sneha', 'shruti', 'aditi',
  'aisha', 'tanvi', 'kritika', 'simran', 'aarohi', 'isha', 'avni',
  // Common Arabic/Middle Eastern names
  'omar', 'ahmed', 'ali', 'hassan', 'hussein', 'khalid', 'mohammed',
  'ibrahim', 'yusuf', 'mustafa', 'tariq', 'salman', 'faisal', 'hamza',
  'fatima', 'aisha', 'zainab', 'maryam', 'huda', 'layla', 'sara',
  // Common East Asian names (romanized, single-word)
  'kenji', 'yuki', 'akira', 'takeshi', 'sakura', 'haruto', 'yuto',
  'hina', 'aoi', 'mei', 'ren', 'sora', 'riku', 'minato',
  // Common African names
  'kwame', 'kofi', 'amara', 'chioma', 'chinwe', 'emeka', 'ngozi',
  'olumide', 'adebayo', 'chidi', 'nneka', 'obiora', 'uchenna',
  // Common European names
  'luca', 'matteo', 'elena', 'sofia', 'hugo', 'leon', 'felix',
  'oscar', 'mila', 'nora', 'clara', 'ida', 'freya', 'astrid',
  'ingrid', 'magnus', 'lars', 'erik', 'olaf', 'ivan', 'dmitri',
  'nikolai', 'sven', 'hans', 'karl', 'franz', 'pierre', 'jean',
  'marie', 'colette', 'renee', 'pascal', 'marco', 'giovanni', 'andrea',
  'giuseppe', 'antonio', 'carlos', 'diego', 'pablo', 'miguel', 'rafael',
  'fernando', 'alejandro', 'lucia', 'carmen', 'rosa', 'elena', 'ines'
];

module.exports = {
  countries,
  cities,
  usStates,
  indianStates,
  genericNames
};
